name: website-ci

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:unit