name: Website CI

on: [ push ]

defaults:
  run:
    working-directory: website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:unit